# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
# - jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# 3. Gem settings
# paginate: 2 # jekyll-paginate > items per page
# paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
author: Kontra klasa # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Kontraklasa # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://fb.com/kontraklasa/
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Zagreb # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Home # Needed for Siteleaf
    output: true
    description: "marksistički kolektiv " # The post list page content
    feature_text: |
      marksistički kolektiv
    feature_image: "https://res.cloudinary.com/dhngozzmz/image/upload/c_fill,g_north_west,h_350,w_619/v1501208257/gas-mask-meeting_me3l6y.jpg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.jpg" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
remote_theme: daviddarnes/alembic
title: "Kontraklasa" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/favicon-16x16.png" # Site logo, also used in jekyll-seo-tag
description: "marksistički kolektiv " # Site description and default description, also used in jekyll-seo-tag
url: "https://vilior.github.io/kontraklasa.org/" # Site url, also used in jekyll-seo-tag
baseurl: ""
# repo: "https://github.com/daviddarnes/alembic"
# email: "me@daviddarnes.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/favicon-16x16.png'
  # 16: '/assets/logos/logo@16px.png'
  # 32: '/assets/logos/logo@32px.png'
  # 96: '/assets/logos/logo@96px.png'
  # 120: '/assets/logos/logo@120px.png'
  # 144: '/assets/logos/logo@144px.png'
  # 180: '/assets/logos/logo@180px.png'
  # 512: '/assets/logos/logo@512px.png'
  # 1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Categories
  url: /categories/
- title: Search
  url: /search/

navigation_footer:
- title: Home
  url: /
- title: About
  url: /about/
- title: Categories
  url: /categories/
- title: Search
  url: /search/


social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/jancorazza
  GitHub: https://github.com/corazza
  Facebook: https://fb.com/kontraklasa
  # link: https://darn.es
  # RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: true
  facebook: true
  Email: true
